-- VOLAKO — schéma complet du MCD.
-- Seules les tables users, refresh_tokens, accounts, categories, transactions
-- ont une logique métier implémentée en V1. Les autres sont créées à vide
-- pour éviter des migrations chaotiques plus tard (transferts, budgets,
-- dettes, crédits, objectifs, récurrence, notifications).

-- ============ V1 : périmètre actif ============

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token      VARCHAR(512) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE accounts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name                    VARCHAR(255) NOT NULL,
    type                    VARCHAR(30) NOT NULL,
    currency                VARCHAR(3) NOT NULL DEFAULT 'MGA',
    allow_negative_balance  BOOLEAN NOT NULL DEFAULT TRUE,
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_accounts_user_id ON accounts (user_id);

CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name       VARCHAR(100) NOT NULL,
    type       VARCHAR(10) NOT NULL,
    is_system  BOOLEAN NOT NULL DEFAULT FALSE,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_categories_user_name_type UNIQUE (user_id, name, type)
);
CREATE INDEX idx_categories_user_id ON categories (user_id);

CREATE TABLE transactions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    account_id        BIGINT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    category_id       BIGINT NOT NULL REFERENCES categories (id),
    type              VARCHAR(10) NOT NULL,
    amount             NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    description       VARCHAR(255),
    transaction_date  DATE NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_transactions_user_id ON transactions (user_id);
CREATE INDEX idx_transactions_account_id ON transactions (account_id);
CREATE INDEX idx_transactions_category_id ON transactions (category_id);
CREATE INDEX idx_transactions_date ON transactions (transaction_date);

-- ============ Hors périmètre V1 : schéma seul, aucune logique métier ============

CREATE TABLE transfers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    from_account_id  BIGINT NOT NULL REFERENCES accounts (id),
    to_account_id    BIGINT NOT NULL REFERENCES accounts (id),
    amount           NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    description      VARCHAR(255),
    transfer_date    DATE NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_transfers_user_id ON transfers (user_id);

CREATE TABLE budgets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id  BIGINT NOT NULL REFERENCES categories (id),
    amount       NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    period_month INT NOT NULL,
    period_year  INT NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_budgets_user_category_period UNIQUE (user_id, category_id, period_month, period_year)
);
CREATE INDEX idx_budgets_user_id ON budgets (user_id);

CREATE TABLE debts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    direction   VARCHAR(20) NOT NULL,
    person_name VARCHAR(255) NOT NULL,
    amount      NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    description VARCHAR(255),
    due_date    DATE,
    status      VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_debts_user_id ON debts (user_id);

CREATE TABLE debt_payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id      BIGINT NOT NULL REFERENCES debts (id) ON DELETE CASCADE,
    account_id   BIGINT NOT NULL REFERENCES accounts (id),
    amount       NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_debt_payments_debt_id ON debt_payments (debt_id);

CREATE TABLE loans (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name             VARCHAR(255) NOT NULL,
    principal_amount NUMERIC(15, 2) NOT NULL CHECK (principal_amount > 0),
    monthly_payment  NUMERIC(15, 2) NOT NULL CHECK (monthly_payment > 0),
    duration_months  INT NOT NULL,
    start_date       DATE NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_loans_user_id ON loans (user_id);

CREATE TABLE loan_payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id      BIGINT NOT NULL REFERENCES loans (id) ON DELETE CASCADE,
    account_id   BIGINT NOT NULL REFERENCES accounts (id),
    amount       NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_loan_payments_loan_id ON loan_payments (loan_id);

CREATE TABLE financial_goals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    target_amount NUMERIC(15, 2) NOT NULL CHECK (target_amount > 0),
    target_date   DATE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_financial_goals_user_id ON financial_goals (user_id);

CREATE TABLE goal_contributions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id            BIGINT NOT NULL REFERENCES financial_goals (id) ON DELETE CASCADE,
    account_id         BIGINT NOT NULL REFERENCES accounts (id),
    amount             NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    contribution_date  DATE NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_goal_contributions_goal_id ON goal_contributions (goal_id);

CREATE TABLE recurring_transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    account_id     BIGINT NOT NULL REFERENCES accounts (id),
    category_id    BIGINT NOT NULL REFERENCES categories (id),
    type           VARCHAR(10) NOT NULL,
    amount         NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    description    VARCHAR(255),
    frequency      VARCHAR(20) NOT NULL,
    next_run_date  DATE NOT NULL,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_recurring_transactions_user_id ON recurring_transactions (user_id);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(50) NOT NULL,
    message    VARCHAR(500) NOT NULL,
    is_read    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notifications_user_id ON notifications (user_id);
